### ISSUE TITLE
App crashes when remove all chats FAB is pressed

### ISSUE THREAD

**Issue by UsernameInvalidException** [HueToYou/ChatExchange#16]
Stacktrace:

```
Process: com.huetoyou.chatexchange, PID: 4787
  java.lang.IllegalStateException: Could not find method removeAllChats(View) in a parent or ancestor Context for android:onClick attribute defined on view class com.github.clans.fab.FloatingActionButton with id 'remove_all_chats_fab'
    at android.view.View$DeclaredOnClickListener.resolveMethod(View.java:4757)
    at android.view.View$DeclaredOnClickListener.onClick(View.java:4716)
    at android.view.View.performClick(View.java:5637)
    at android.view.View$PerformClick.run(View.java:22433)
    at android.os.Handler.handleCallback(Handler.java:751)
    at android.os.Handler.dispatchMessage(Handler.java:95)
    at android.os.Looper.loop(Looper.java:154)
    at android.app.ActivityThread.main(ActivityThread.java:6186)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:889)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:779)
```

**Comment by UsernameInvalidException** [comment]
Fixed in a1a1bb4
